### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by JimKarlson** [leeej84/PowerScale#18]
In the dashboard: 

**A.  History section:  there is a section of URLs for listing the historical dashboards from other days. Suggestions:**  

1. Update the height of this section in your template file; then when users select longer retention windows the URLs/Dates will all fit in the space properly.  We've found that 120px seems to work nicely. 
2. Update the date format to be mm-dd-yyyy.  Current format where it can go to m-d-yyyy breaks the sorting of dates and you end up with 8-10-2020 showing up before 8-2-2020 in the listing. 

**B. Titles in the dashboard - with a number of farms it's not so easy to remember which dashboard you are reviewing; adding elements to the Create Config File.ps1**
1. Ask for the user's preferred name/title for the specific instantiation of PowerScale. Use that name in both the <Title> section and the H1 section of the dashboard template.  Then the tab has the name and the displayed dashboard has the name on it.

**Comment by leeej84** [comment]
Thanks Jim, I'll get these pulled together.

**Comment by leeej84** [comment]
So, the date string is a strange one. I think this may have more to do with your settings on the machine. 

Can you run this in a PowerShell screen? 
(Get-Date 9/9/20).ToShortDateString()

Let me see your output?

This is what I get - 09/09/2020

**Comment by leeej84** [comment]
Hi Jim, In the current branch you will find a test version, please put it in testing and not straight to production though. I have added other things such as a restrictive scale down method where you can specify how many machines get powered off rather than going straight to your target point.

There are two new config entries:
instanceName
dateFormat

I put the specific example for you in the comments. Let me know how you get on.

**Comment by leeej84** [comment]
Dashboards amends applied successfully and shown in testing, closing the issue.
